name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend-image ./backend

      - name: Build frontend image
        run: docker build -t frontend-image ./frontend

      - name: Run docker-compose up (detached)
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

      - name: Stop and clean up
        run: docker-compose down 